name: "Upload Website"

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Deploying ${{ github.ref_name }} ${{ github.ref_type }}\"}' ${{ vars.NOTIFICATION_HOOK }}"
    - uses: actions/checkout@master
    - name: "Use Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Copy files to the s3 website content bucket
      run:
          aws s3 sync out s3://${{ secrets.AWS_S3_BUCKET }} --delete
    - name: Notify deployment completion
      run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Deployment for ${{ github.ref_name }} ${{ github.ref_type }} done\"}' ${{ vars.NOTIFICATION_HOOK }}"
      
  invalidate:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Invalidate cache
      run:
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/*"
    - name: Notify invalidation completion
      run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Static site cache invalidated for ${{ github.ref_name }} ${{ github.ref_type }}.  All should be good :rocket:\"}' ${{ vars.NOTIFICATION_HOOK }}"
